//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Da_ne_bude_da_nije_video
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Film
    {
        public int ID { get; set; }
        [Required]
        [RegularExpression(@"[a-zA-Z ]{2,30}$", ErrorMessage = "Unesite vrednost izmedju 2 i 30 karaktera")]
        public string Naziv { get; set; }
        [Required]
        public string Zanr { get; set; }
        [Required]
        [RegularExpression(@"^(\d{4})$", ErrorMessage = "Unesite broj od 4 cifre")]
        public int Godina { get; set; }
        [Required]
        [RegularExpression(@"^(\d{2,3})$", ErrorMessage = "Unesite broj od 2 ili 3 cifre")]
        public int Trajanje { get; set; }
        [Required]
        public double Ocena { get; set; }
        [Required]
        public string Slika { get; set; }
        public HttpPostedFileBase ImageUpload { get; set; }
        [Required]
        public string Video { get; set; }
    }
}
