//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Da_ne_bude_da_nije_video
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Korisnik
    {
        public int ID { get; set; }
        [Required]
        [RegularExpression(@"[a-zA-Z ]{2,30}$", ErrorMessage = "Unesite vrednost izmedju 2 i 30 karaktera")]
        public string Ime { get; set; }
        [Required]
        [RegularExpression(@"[a-zA-Z ]{2,30}$", ErrorMessage = "Unesite vrednost izmedju 2 i 30 karaktera")]
        public string Prezime { get; set; }
        [Required]
        [Display(Name = "Korisnicko ime")]
        [RegularExpression(@"[a-zA-Z ]{2,30}$", ErrorMessage = "Unesite vrednost izmedju 2 i 30 karaktera")]
        public string KorisnickoIme { get; set; }
        [Required]
       // [RegularExpression(@"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{4,8}$")]
        public string Lozinka { get; set; }
        public int PravoPristupa { get; set; }
    }
}
